### ISSUE TITLE
Can't update to version 1.0.4

### ISSUE THREAD

**Issue by varlux** [geolink/opentracker-arduino-board#2]
This is the error I obtain if I try to update to version 1.0.4:

Errore durante lo scaricamento di https://github.com/geolink/opentracker-bossa/releases/download/1.5-opentracker/bossac-1.5-opentracker-x86_64-linux-gnu.tar.gz
java.lang.RuntimeException: java.lang.Exception: Errore durante lo scaricamento di https://github.com/geolink/opentracker-bossa/releases/download/1.5-opentracker/bossac-1.5-opentracker-x86_64-linux-gnu.tar.gz
    at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onInstallPressed$20(ContributionManagerUI.java:176)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Exception: Errore durante lo scaricamento di https://github.com/geolink/opentracker-bossa/releases/download/1.5-opentracker/bossac-1.5-opentracker-x86_64-linux-gnu.tar.gz
    at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:113)
    at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:67)
    at cc.arduino.contributions.packages.ContributionInstaller.install(ContributionInstaller.java:111)
    at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onInstallPressed$20(ContributionManagerUI.java:173)
    ... 1 more
Caused by: java.io.IOException: Received invalid http status code from server: 416
    at cc.arduino.utils.network.FileDownloader.downloadFile(FileDownloader.java:194)
    at cc.arduino.utils.network.FileDownloader.download(FileDownloader.java:128)
    at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:111)
    ... 4 more

Can you help me?

Thanks

**Comment by ppescher** [comment]
See the stack trace: "Caused by: java.io.IOException: Received invalid http status code from server: 416"

"416 Range Not Satisfiable (RFC 7233): The client has asked for a portion of the file (byte serving), but the server cannot supply that portion."

It seems the IDE wants to download only a portion of the file, but the server does not support that request, and the client is not prepared to handle this situation. You might want to open an issue for the Arduino IDE.
Try to delete partial files downloaded by the IDE: look for the file "1.5-opentracker/bossac-1.5-opentracker-x86_64-linux-gnu.tar.gz" in the folder "%LocalAppData%\Arduino15\staging\packages". Then try again.

**Comment by varlux** [comment]
OK Paolo, I solved the problem thanks to your suggestions.

But.......

I followed the instructions to update the board...... is it a problem of the IDE, or of the server?
I will face this problem for the next update?

Thanks

**Comment by ppescher** [comment]
Glad you solved. I really don't know who is the culprit. I think the IDE should be more robust and handle the situation by downloading the whole file again. It might have been an occasional network or server issue, but the client should be prepared to handle it.
